services:
  postgres:
    container_name: postgres
    image: postgres:18-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10

  goose:
    container_name: goose
    image: gomicro/goose:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://postgres:postgres@postgres:5432/postgres
    volumes:
      - ./migrations:/migrations
    command: ["goose", "-dir", "/migrations", "up"]

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      goose:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
