// Code generated by mockery. DO NOT EDIT.

package mockdepartment

import (
	department "github.com/Geriler/hitalent/internal/domain/department"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *MockRepository) Create(_a0 *department.Department) (*department.Department, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *department.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(*department.Department) (*department.Department, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*department.Department) *department.Department); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*department.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(*department.Department) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *department.Department
func (_e *MockRepository_Expecter) Create(_a0 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *MockRepository_Create_Call) Run(run func(_a0 *department.Department)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*department.Department))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 *department.Department, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(*department.Department) (*department.Department, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockRepository) Delete(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockRepository_Expecter) Delete(id interface{}) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(id int64)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(_a0 error) *MockRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(int64) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByNameAndParent provides a mock function with given fields: name, parentID
func (_m *MockRepository) ExistsByNameAndParent(name string, parentID *int64) (bool, error) {
	ret := _m.Called(name, parentID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByNameAndParent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *int64) (bool, error)); ok {
		return rf(name, parentID)
	}
	if rf, ok := ret.Get(0).(func(string, *int64) bool); ok {
		r0 = rf(name, parentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, *int64) error); ok {
		r1 = rf(name, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ExistsByNameAndParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByNameAndParent'
type MockRepository_ExistsByNameAndParent_Call struct {
	*mock.Call
}

// ExistsByNameAndParent is a helper method to define mock.On call
//   - name string
//   - parentID *int64
func (_e *MockRepository_Expecter) ExistsByNameAndParent(name interface{}, parentID interface{}) *MockRepository_ExistsByNameAndParent_Call {
	return &MockRepository_ExistsByNameAndParent_Call{Call: _e.mock.On("ExistsByNameAndParent", name, parentID)}
}

func (_c *MockRepository_ExistsByNameAndParent_Call) Run(run func(name string, parentID *int64)) *MockRepository_ExistsByNameAndParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*int64))
	})
	return _c
}

func (_c *MockRepository_ExistsByNameAndParent_Call) Return(_a0 bool, _a1 error) *MockRepository_ExistsByNameAndParent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ExistsByNameAndParent_Call) RunAndReturn(run func(string, *int64) (bool, error)) *MockRepository_ExistsByNameAndParent_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockRepository) GetByID(id int64) (*department.Department, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *department.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*department.Department, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *department.Department); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*department.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int64
func (_e *MockRepository_Expecter) GetByID(id interface{}) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(id int64)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(_a0 *department.Department, _a1 error) *MockRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(int64) (*department.Department, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildren provides a mock function with given fields: id, depth
func (_m *MockRepository) GetChildren(id int64, depth int) ([]*department.Department, error) {
	ret := _m.Called(id, depth)

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []*department.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) ([]*department.Department, error)); ok {
		return rf(id, depth)
	}
	if rf, ok := ret.Get(0).(func(int64, int) []*department.Department); ok {
		r0 = rf(id, depth)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*department.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(id, depth)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildren'
type MockRepository_GetChildren_Call struct {
	*mock.Call
}

// GetChildren is a helper method to define mock.On call
//   - id int64
//   - depth int
func (_e *MockRepository_Expecter) GetChildren(id interface{}, depth interface{}) *MockRepository_GetChildren_Call {
	return &MockRepository_GetChildren_Call{Call: _e.mock.On("GetChildren", id, depth)}
}

func (_c *MockRepository_GetChildren_Call) Run(run func(id int64, depth int)) *MockRepository_GetChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_GetChildren_Call) Return(_a0 []*department.Department, _a1 error) *MockRepository_GetChildren_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetChildren_Call) RunAndReturn(run func(int64, int) ([]*department.Department, error)) *MockRepository_GetChildren_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubtreeIDs provides a mock function with given fields: id
func (_m *MockRepository) GetSubtreeIDs(id int64) ([]int64, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSubtreeIDs")
	}

	var r0 []int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]int64, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) []int64); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetSubtreeIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubtreeIDs'
type MockRepository_GetSubtreeIDs_Call struct {
	*mock.Call
}

// GetSubtreeIDs is a helper method to define mock.On call
//   - id int64
func (_e *MockRepository_Expecter) GetSubtreeIDs(id interface{}) *MockRepository_GetSubtreeIDs_Call {
	return &MockRepository_GetSubtreeIDs_Call{Call: _e.mock.On("GetSubtreeIDs", id)}
}

func (_c *MockRepository_GetSubtreeIDs_Call) Run(run func(id int64)) *MockRepository_GetSubtreeIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockRepository_GetSubtreeIDs_Call) Return(_a0 []int64, _a1 error) *MockRepository_GetSubtreeIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetSubtreeIDs_Call) RunAndReturn(run func(int64) ([]int64, error)) *MockRepository_GetSubtreeIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: id, _a1
func (_m *MockRepository) Update(id int64, _a1 *department.Department) (*department.Department, error) {
	ret := _m.Called(id, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *department.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, *department.Department) (*department.Department, error)); ok {
		return rf(id, _a1)
	}
	if rf, ok := ret.Get(0).(func(int64, *department.Department) *department.Department); ok {
		r0 = rf(id, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*department.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, *department.Department) error); ok {
		r1 = rf(id, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id int64
//   - _a1 *department.Department
func (_e *MockRepository_Expecter) Update(id interface{}, _a1 interface{}) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", id, _a1)}
}

func (_c *MockRepository_Update_Call) Run(run func(id int64, _a1 *department.Department)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(*department.Department))
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(_a0 *department.Department, _a1 error) *MockRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(int64, *department.Department) (*department.Department, error)) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
