// Code generated by mockery. DO NOT EDIT.

package mockemployee

import (
	employee "github.com/Geriler/hitalent/internal/domain/employee"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0
func (_m *MockRepository) Create(_a0 *employee.Employee) (*employee.Employee, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *employee.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(*employee.Employee) (*employee.Employee, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*employee.Employee) *employee.Employee); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*employee.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(*employee.Employee) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 *employee.Employee
func (_e *MockRepository_Expecter) Create(_a0 interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", _a0)}
}

func (_c *MockRepository_Create_Call) Run(run func(_a0 *employee.Employee)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*employee.Employee))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 *employee.Employee, _a1 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(*employee.Employee) (*employee.Employee, error)) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByDepartmentID provides a mock function with given fields: departmentID
func (_m *MockRepository) GetByDepartmentID(departmentID int64) ([]*employee.Employee, error) {
	ret := _m.Called(departmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByDepartmentID")
	}

	var r0 []*employee.Employee
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]*employee.Employee, error)); ok {
		return rf(departmentID)
	}
	if rf, ok := ret.Get(0).(func(int64) []*employee.Employee); ok {
		r0 = rf(departmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*employee.Employee)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(departmentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetByDepartmentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByDepartmentID'
type MockRepository_GetByDepartmentID_Call struct {
	*mock.Call
}

// GetByDepartmentID is a helper method to define mock.On call
//   - departmentID int64
func (_e *MockRepository_Expecter) GetByDepartmentID(departmentID interface{}) *MockRepository_GetByDepartmentID_Call {
	return &MockRepository_GetByDepartmentID_Call{Call: _e.mock.On("GetByDepartmentID", departmentID)}
}

func (_c *MockRepository_GetByDepartmentID_Call) Run(run func(departmentID int64)) *MockRepository_GetByDepartmentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockRepository_GetByDepartmentID_Call) Return(_a0 []*employee.Employee, _a1 error) *MockRepository_GetByDepartmentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetByDepartmentID_Call) RunAndReturn(run func(int64) ([]*employee.Employee, error)) *MockRepository_GetByDepartmentID_Call {
	_c.Call.Return(run)
	return _c
}

// ReassignEmployees provides a mock function with given fields: fromDepartmentID, toDepartmentID
func (_m *MockRepository) ReassignEmployees(fromDepartmentID int64, toDepartmentID int64) error {
	ret := _m.Called(fromDepartmentID, toDepartmentID)

	if len(ret) == 0 {
		panic("no return value specified for ReassignEmployees")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(fromDepartmentID, toDepartmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ReassignEmployees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReassignEmployees'
type MockRepository_ReassignEmployees_Call struct {
	*mock.Call
}

// ReassignEmployees is a helper method to define mock.On call
//   - fromDepartmentID int64
//   - toDepartmentID int64
func (_e *MockRepository_Expecter) ReassignEmployees(fromDepartmentID interface{}, toDepartmentID interface{}) *MockRepository_ReassignEmployees_Call {
	return &MockRepository_ReassignEmployees_Call{Call: _e.mock.On("ReassignEmployees", fromDepartmentID, toDepartmentID)}
}

func (_c *MockRepository_ReassignEmployees_Call) Run(run func(fromDepartmentID int64, toDepartmentID int64)) *MockRepository_ReassignEmployees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *MockRepository_ReassignEmployees_Call) Return(_a0 error) *MockRepository_ReassignEmployees_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ReassignEmployees_Call) RunAndReturn(run func(int64, int64) error) *MockRepository_ReassignEmployees_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
